version: '2'
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
   # volumes:
   #   - .:/myapp
    ports:
      - "3000:3000"
    environment: 
      - CONTRAST__API__URL=https://app.contrastsecurity.com/Contrast
      - CONTRAST__API__API_KEY={agent API KEY}
      - CONTRAST__API__SERVICE_KEY={agent Service key}
      - CONTRAST__API__USER_NAME={agent user name}
      - CONTRAST__APPLICATION__NAME=RailsGoat
      - CONTRAST__SERVER__NAME=DockerRailServer